In [2]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
import pickle

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Preprocess the data 
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [7]:
## Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [8]:
# one - hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
## combine the encoded columns with the original dataframe
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
## split the data into features and target variable
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [12]:
## split the data in training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
## save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

with open('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo, f)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

## ANN regression problem statement

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [16]:
## build the ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='linear') # output layer for regression
])

## compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])

model.summary()

c:\Users\anmol\OneDrive\Desktop\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

#set up tensoboarsd
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [18]:
### set up early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [19]:
## TRain the model 
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - loss: 13381711872.0000 - mean_absolute_error: 100368.1562 - val_loss: 13001784320.0000 - val_mean_absolute_error: 98491.4062
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 13221952512.0000 - mean_absolute_error: 99577.1953 - val_loss: 12688859136.0000 - val_mean_absolute_error: 96908.7109
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 12672779264.0000 - mean_absolute_error: 96857.1562 - val_loss: 11899950080.0000 - val_mean_absolute_error: 92919.7578
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 11593704448.0000 - mean_absolute_error: 91524.8828 - val_loss: 10588038144.0000 - val_mean_absolute_error: 86283.1406
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10040205312.0000 - mean_absolute_error: 83728.7266 - val_loss: 8900481024.0000 - val_mean_absolute_error: 77808.4922
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8225072640.0000 - mean_absolute_error: 74627.0859 - val_loss: 7120503296.0000 - val_mean_absolute_error: 68993.1406
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6474151424.0000 - mean_absolute_error: 65785.7500 - val_loss: 5575250432.0000 - val_mean_absolute_error: 61299.3711
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5085310976.0000 - mean_absolute_error: 58685.6289 - val_loss: 4495647232.0000 - val_mean_absolute_error: 55818.4805
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4192297216.0000 - mean_absolute_error: 54110.7383 - val_loss: 3894443776.0000 - val_mean_absolute_error: 52729.7227
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3728088576.0000 - mean_absolute_error: 51728.0938 - val_loss: 3623791360.0000 - val_mean_absolute_error: 51415.8516
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3524434688.0000 - mean_absolute_error: 50683.5742 - val_loss: 3520241408.0000 - val_mean_absolute_error: 50926.0352
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3441159936.0000 - mean_absolute_error: 50268.8945 - val_loss: 3479203328.0000 - val_mean_absolute_error: 50774.8984
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3404470272.0000 - mean_absolute_error: 50080.9023 - val_loss: 3457576960.0000 - val_mean_absolute_error: 50672.7461
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3384476928.0000 - mean_absolute_error: 49979.5000 - val_loss: 3442621952.0000 - val_mean_absolute_error: 50586.2930
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3371359232.0000 - mean_absolute_error: 49906.5117 - val_loss: 3432824576.0000 - val_mean_absolute_error: 50532.6875
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3361809664.0000 - mean_absolute_error: 49857.2109 - val_loss: 3422698752.0000 - val_mean_absolute_error: 50474.4492
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3354052864.0000 - mean_absolute_error: 49820.7773 - val_loss: 3413884160.0000 - val_mean_absolute_error: 50426.4453
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3347667968.0000 - mean_absolute_error: 49781.8164 - val_loss: 3408751104.0000 - val_mean_absolute_error: 50401.1367
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3342418432.0000 - mean_absolute_error: 49747.7617 - val_loss: 3402307840.0000 - val_mean_absolute_error: 50367.5078
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3337638656.0000 - mean_absolute_error: 49723.1797 - val_loss: 3398538752.0000 - val_mean_absolute_error: 50350.9453
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3333750784.0000 - mean_absolute_error: 49698.3086 - val_loss: 3393711872.0000 - val_mean_absolute_error: 50325.6641
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3330201856.0000 - mean_absolute_error: 49677.9727 - val_loss: 3391465728.0000 - val_mean_absolute_error: 50320.5938
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3326981376.0000 - mean_absolute_error: 49657.6875 - val_loss: 3387661824.0000 - val_mean_absolute_error: 50300.9883
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3324304128.0000 - mean_absolute_error: 49641.8750 - val_loss: 3384371200.0000 - val_mean_absolute_error: 50285.2969
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3321552896.0000 - mean_absolute_error: 49629.5078 - val_loss: 3382126080.0000 - val_mean_absolute_error: 50275.2695
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3319454720.0000 - mean_absolute_error: 49614.0586 - val_loss: 3379416576.0000 - val_mean_absolute_error: 50261.9375
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3317421824.0000 - mean_absolute_error: 49602.9570 - val_loss: 3377866496.0000 - val_mean_absolute_error: 50254.1719
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3314944000.0000 - mean_absolute_error: 49585.7539 - val_loss: 3375288576.0000 - val_mean_absolute_error: 50241.7695
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3313401600.0000 - mean_absolute_error: 49581.4023 - val_loss: 3372781824.0000 - val_mean_absolute_error: 50227.7656
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3312294144.0000 - mean_absolute_error: 49570.1914 - val_loss: 3373146624.0000 - val_mean_absolute_error: 50234.1328
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3310580224.0000 - mean_absolute_error: 49560.6211 - val_loss: 3370517760.0000 - val_mean_absolute_error: 50216.6250
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3309343744.0000 - mean_absolute_error: 49554.2070 - val_loss: 3370508800.0000 - val_mean_absolute_error: 50218.7969
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3308187136.0000 - mean_absolute_error: 49548.9375 - val_loss: 3368726016.0000 - val_mean_absolute_error: 50210.6719
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3306741760.0000 - mean_absolute_error: 49538.4883 - val_loss: 3367644928.0000 - val_mean_absolute_error: 50203.8633
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3305806336.0000 - mean_absolute_error: 49531.5664 - val_loss: 3367460608.0000 - val_mean_absolute_error: 50204.0000
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3304782592.0000 - mean_absolute_error: 49526.8320 - val_loss: 3365055232.0000 - val_mean_absolute_error: 50184.7812
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3303884544.0000 - mean_absolute_error: 49519.2266 - val_loss: 3365133824.0000 - val_mean_absolute_error: 50184.5234
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3303109376.0000 - mean_absolute_error: 49508.9141 - val_loss: 3365765888.0000 - val_mean_absolute_error: 50190.9023
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3301986048.0000 - mean_absolute_error: 49506.4023 - val_loss: 3363090176.0000 - val_mean_absolute_error: 50173.3359
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3301283328.0000 - mean_absolute_error: 49502.2148 - val_loss: 3363483648.0000 - val_mean_absolute_error: 50177.2070
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3300435968.0000 - mean_absolute_error: 49492.4258 - val_loss: 3363699456.0000 - val_mean_absolute_error: 50179.5625
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3299837952.0000 - mean_absolute_error: 49485.9219 - val_loss: 3364524032.0000 - val_mean_absolute_error: 50186.5508
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3298950656.0000 - mean_absolute_error: 49492.5703 - val_loss: 3360697344.0000 - val_mean_absolute_error: 50156.5391
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3298384128.0000 - mean_absolute_error: 49482.8477 - val_loss: 3362289664.0000 - val_mean_absolute_error: 50173.3867
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3297949952.0000 - mean_absolute_error: 49481.1094 - val_loss: 3361362176.0000 - val_mean_absolute_error: 50162.8984
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3297591552.0000 - mean_absolute_error: 49474.7188 - val_loss: 3360132864.0000 - val_mean_absolute_error: 50154.5977
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3296521216.0000 - mean_absolute_error: 49469.5898 - val_loss: 3361336576.0000 - val_mean_absolute_error: 50166.5625
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3295805440.0000 - mean_absolute_error: 49462.8789 - val_loss: 3361225216.0000 - val_mean_absolute_error: 50165.9023
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3295212544.0000 - mean_absolute_error: 49457.4258 - val_loss: 3360872192.0000 - val_mean_absolute_error: 50163.7148
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 3295067904.0000 - mean_absolute_error: 49455.5312 - val_loss: 3361593856.0000 - val_mean_absolute_error: 50170.1133
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3294534912.0000 - mean_absolute_error: 49451.4961 - val_loss: 3361470720.0000 - val_mean_absolute_error: 50171.7227
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3293881856.0000 - mean_absolute_error: 49449.7734 - val_loss: 3360341248.0000 - val_mean_absolute_error: 50160.4844
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3293513728.0000 - mean_absolute_error: 49446.8203 - val_loss: 3360883712.0000 - val_mean_absolute_error: 50164.0859
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3292623616.0000 - mean_absolute_error: 49438.1562 - val_loss: 3359914752.0000 - val_mean_absolute_error: 50155.4062
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3292411136.0000 - mean_absolute_error: 49434.7461 - val_loss: 3361283072.0000 - val_mean_absolute_error: 50163.9375
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3292264960.0000 - mean_absolute_error: 49438.7422 - val_loss: 3360918528.0000 - val_mean_absolute_error: 50162.9258
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3291559936.0000 - mean_absolute_error: 49434.1875 - val_loss: 3360656128.0000 - val_mean_absolute_error: 50164.8828
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3291111424.0000 - mean_absolute_error: 49427.4453 - val_loss: 3359814400.0000 - val_mean_absolute_error: 50156.0586
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3290737664.0000 - mean_absolute_error: 49422.6719 - val_loss: 3359060480.0000 - val_mean_absolute_error: 50151.2734
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3290147328.0000 - mean_absolute_error: 49421.2031 - val_loss: 3360445440.0000 - val_mean_absolute_error: 50160.9375
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3290216192.0000 - mean_absolute_error: 49417.7656 - val_loss: 3360218112.0000 - val_mean_absolute_error: 50158.7578
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3289369344.0000 - mean_absolute_error: 49419.7734 - val_loss: 3359950848.0000 - val_mean_absolute_error: 50157.6211
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3289056768.0000 - mean_absolute_error: 49411.4492 - val_loss: 3359198464.0000 - val_mean_absolute_error: 50150.3008
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3288564480.0000 - mean_absolute_error: 49407.6133 - val_loss: 3359216640.0000 - val_mean_absolute_error: 50153.0078
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3288028672.0000 - mean_absolute_error: 49403.7891 - val_loss: 3360630272.0000 - val_mean_absolute_error: 50163.5898
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 3288247040.0000 - mean_absolute_error: 49405.2969 - val_loss: 3359100672.0000 - val_mean_absolute_error: 50151.3633
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3288094720.0000 - mean_absolute_error: 49407.3633 - val_loss: 3359533568.0000 - val_mean_absolute_error: 50151.9414
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3287248128.0000 - mean_absolute_error: 49397.7070 - val_loss: 3359725056.0000 - val_mean_absolute_error: 50158.2695
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3286989312.0000 - mean_absolute_error: 49394.3555 - val_loss: 3360017408.0000 - val_mean_absolute_error: 50159.9414

In [26]:
%pip install tensorboard

Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in .\venv\Lib\site-packages (from tensorboard) (1.83.1)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.3)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorboard) (7.36.1)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (83.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [29]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [31]:
import sys
import os

tb_path = os.path.join(
    os.path.dirname(sys.executable),
    "Scripts",
    "tensorboard.exe"
)

print("Python:", sys.executable)
print("TensorBoard:", tb_path)
print("Exists:", os.path.exists(tb_path))

Python: c:\Users\anmol\OneDrive\Desktop\ANN Classification\venv\python.exe
TensorBoard: c:\Users\anmol\OneDrive\Desktop\ANN Classification\venv\Scripts\tensorboard.exe
Exists: True

In [32]:
os.environ["TENSORBOARD_BINARY"] = tb_path

In [33]:
%tensorboard --logdir regressionlogs/fit

In [34]:
## evaluate model on the data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3359060480.0000 - mean_absolute_error: 50151.2734
Test Loss: 3359060480.0, Test MAE: 50151.2734375

In [ ]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

: